### ISSUE TITLE
Pringa-hub-2-Low: Sign up validation

### ISSUE THREAD

**Issue by javnievic** [pringa-uvlhub/uvlhub#6]
As a user, I want to receive an email confirmation after signing up to complete my account registration, ensuring that my email address is valid before accessing all features.

Currently, users can sign up but are not required to confirm their email address before logging into their accounts. This can lead to users entering invalid or incorrect email addresses during the sign-up process, which may cause issues with communication and account recovery.

**Comment by pabdiaord** [comment]
Branch: feature/sign-up-validation
